import {ArbitrarySize, FluentPick} from './types'
import {ChainedArbitrary, FilteredArbitrary, MappedArbitrary, NoArbitrary} from './internal'
import {stringify} from './util'

export abstract class Arbitrary<A> {

  /**
   * The number of elements that can be generated by this `Arbitrary`.
   *
   * The returned size can be exact or an estimation.
   */
  abstract size(): ArbitrarySize

  /**
   * Generates a random element. This operation is stateless.
   */
  abstract pick(): FluentPick<A> | undefined

  /**
   * Returns `true` if this `Arbitrary` can generate a given element.
   *
   * In cases where the set of possible elements is unknown, this operation is expected to be optimistic - it should
   * return `false` only when a pick is guaranteed not to be generatable.
   *
   * TODO: should we include an "unknown" result?
   */
  abstract canGenerate<B extends A>(pick: FluentPick<B>): boolean

  /**
   * Returns a sample of picks of a given size. Sample might contain repeated values
   * and corner cases are not taken into account.
   */
  sample(sampleSize = 10, currSample: FluentPick<A>[] = []): FluentPick<A>[] {
    const result: FluentPick<A>[] = sampleSize <= currSample.length ? [] : currSample

    for (let i = result.length; i < sampleSize; i++) {
      const pick = this.pick()
      if (pick) result.push(pick)
      else break
    }

    return result
  }

  /**
   * Returns a sample of picks of a given size withour replacement. Sample will
   * not contain repeated values. Corner cases are not taken into account.
   */
  sampleUnique(sampleSize = 10, currSample: FluentPick<A>[] = []): FluentPick<A>[] {
    const result = new Map<string, FluentPick<A>>()

    if (sampleSize > currSample.length) {
      for (const k in currSample)
        result.set(stringify(currSample[k].value), currSample[k])
    }

    const initialSize = this.size()
    let bagSize = Math.min(sampleSize, initialSize.value)

    while (result.size < bagSize) {
      const r = this.pick()
      if (!r) break
      if (!result.has(stringify(r.value))) result.set(stringify(r.value), r)
      if (initialSize.type !== 'exact') bagSize = Math.min(sampleSize, this.size().value)
    }

    return Array.from(result.values())
  }

  /**
   * The special cases for this arbitrary, which can be used during sampling to give
   * higher weight to certain elements.
   */
  cornerCases(): FluentPick<A>[] { return [] }

  /**
   * Returns a sample of picks of a given size. Sample might contain repeated values
   * and might be biased toward corner cases (depending on the specific arbitrary
   * implementing or not the cornerCases method).
   */
  sampleWithBias(sampleSize = 10, currSample: FluentPick<A>[] = []): FluentPick<A>[] {
    currSample = currSample.concat(this.cornerCases())

    if (sampleSize <= currSample.length)
      return this.sample(sampleSize)

    return this.sample(sampleSize, currSample)
  }

  /**
   * Returns a sample of picks of a given size. Sample will not contain repeated values
   * and might be biased toward corner cases (depending on the specific arbitrary
   * implementing or not the cornerCases method).
   */
  sampleUniqueWithBias(sampleSize = 10, currSample: FluentPick<A>[] = []): FluentPick<A>[] {
    currSample = [...new Set(currSample.concat(this.cornerCases()))]

    if (sampleSize <= currSample.length)
      return this.sampleUnique(sampleSize)

    return this.sampleUnique(sampleSize, currSample)
  }

  /**
   * Given a pick known to falsify a property, returns a new arbitrary with simpler cases to be tested. This is part of
   * FluentCheck's behavior of searching for simpler counter-examples after one is found.
   */
  shrink<B extends A>(_initial: FluentPick<B>): Arbitrary<A> {
    return NoArbitrary
  }

  map<B>(f: (a: A) => B): Arbitrary<B> { return new MappedArbitrary(this, f) }
  filter(f: (a: A) => boolean): Arbitrary<A> { return new FilteredArbitrary(this, f) }
  chain<B>(f: (a: A) => Arbitrary<B>): Arbitrary<B> { return new ChainedArbitrary(this, f) }

  toString(depth = 0): string { return ' '.repeat(depth * 2) + `Base Arbitrary: ${this.constructor.name}`  }
}
